name: AppConfiguration-Emulator CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  security-events: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger trx
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/*.trx"